POST http://localhost:4000/api/login
Content-Type: application/json

{
  "email": "ihor@uplab.io",
  "password": "1234"
}

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "ihor@uplab.io",
  "password": "1234"
}

###

GET http://localhost:4000/api/auth/greet
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJpaG9yQHVwbGFiLmlvIiwiaWF0IjoxNjI1MjQ4MDU5LCJleHAiOjE2NTY3ODQwNTl9.T-ZY5Nheccj2ojhL8S-AV4iTb2jTa29KdUU9UBR6vKs

###

GET http://localhost:4000/api/auth/me
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJpaG9yQHVwbGFiLmlvIiwiaWF0IjoxNjI1MjQ4MDU5LCJleHAiOjE2NTY3ODQwNTl9.T-ZY5Nheccj2ojhL8S-AV4iTb2jTa29KdUU9UBR6vKs

###

POST http://localhost:4000/api/auth/logout
Content-Type: application/json

{
@@ -18,7 +40,7 @@ Content-Type: application/json

###

POST http://localhost:4000/api/token
POST http://localhost:4000/api/auth/token
Content-Type: application/json

{
@@ -27,7 +49,7 @@ Content-Type: application/json

###

GET http://localhost:4000/api/hello
GET http://localhost:4000/api/auth/hello
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJpaG9yQHVwbGFiLmlvIiwiaWF0IjoxNjIzNjg5NTA2LCJleHAiOjE2MjM2ODk4MDZ9.uPx-RoaI2QPS6hrBIWzFDZpqQowqnepesCrWw1fE-Fs
